using System.Linq;
using NHibernate.SubclassFormulaBug.Entities;

namespace NHibernate.SubclassFormulaBug.Tests;

[TestFixture]
public class FormulaMappedPropertyTests
{
    [Test]
    public void QueryShouldReturnExpectedResultsForFormulaPropertyInJoinedSubclasses()
    {
        using var sessionFactory = SessionFactoryCreator.GetSessionFactory();
        using var connection = AdoDbInitialiser.GetConnection();
        connection.Open();
        using var session = sessionFactory.WithOptions().Connection(connection).Interceptor(new SqlWritingInterceptor()).OpenSession();
        
        AdoDbInitialiser.CreateSchema(connection);
        AdoDbInitialiser.AddData(connection);

        var results = (from person in session.Query<Person>()
                       from animal in person.Pets
                       where person.Name == "Joe"
                       // Note that the Summary values from this query are expected to be generated by SQL formula
                       select animal.Summary)
           .ToList();

        var expected = new[]
        {
            "Dog, breed 5, 5.6 KG",
            "Bird, breed 4, Red"
        };
        
        Assert.That(results, Is.EquivalentTo(expected));
    }
}